title: "Guacamaya Lab"
description: "Guacamaya Lab - An online notebook â€” unfinished, evolving, honest."
theme: jekyll-theme-cayman
future: true

# Optional: if you use a custom domain later
# url: "https://guacamayalab.com"
